name: Install Nginx on Ubuntu

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  install-nginx:
    runs-on: ubuntu-latest

    steps:


      - name: Update apt and install Nginx
        run: |
          sudo apt update
          sudo apt install -y nginx

      - name: Check Nginx status
        run: |
          sudo systemctl status nginx --no-pager

      - name: Verify Nginx is running
        run: curl -I http://localhost
